# Generated by Django 5.0.6 on 2024-07-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbountMeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Details', models.TextField(max_length=500)),
                ('Name', models.CharField(max_length=50)),
                ('Date_of_birth', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('Zip_code', models.PositiveIntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CarouselModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('hilight_title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='MySkillModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Skill_name', models.CharField(max_length=50)),
                ('Skill_percentange', models.IntegerField()),
            ],
        ),
    ]
