# Generated by Django 5.0.6 on 2024-07-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True, max_length=500, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.PositiveIntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(blank=True, max_length=50, null=True)),
                ('project_name', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_images/')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('details', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AbountMeModel',
        ),
        migrations.RemoveField(
            model_name='carouselmodel',
            name='hilight_title',
        ),
        migrations.RemoveField(
            model_name='myskillmodel',
            name='Skill_name',
        ),
        migrations.RemoveField(
            model_name='myskillmodel',
            name='Skill_percentange',
        ),
        migrations.AddField(
            model_name='carouselmodel',
            name='highlight_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myskillmodel',
            name='last_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myskillmodel',
            name='last_week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myskillmodel',
            name='skill_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carouselmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='carousel_images/'),
        ),
        migrations.AlterField(
            model_name='carouselmodel',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='myskillmodel',
            name='skill_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
