# Generated by Django 5.0.6 on 2024-07-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_aboutmemodel_my_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmemodel',
            name='details',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aboutmemodel',
            name='my_intro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
