# Generated by Django 5.0.6 on 2024-07-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_workdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmemodel',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='aboutmemodel',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
