# Generated by Django 5.0.6 on 2024-07-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_aboutmemodel_phone_alter_aboutmemodel_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmemodel',
            name='details',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='aboutmemodel',
            name='my_intro',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
