# Generated by Django 5.0.6 on 2024-07-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_aboutmemodel_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='project_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
